name: Python checks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  unittest:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Compile
        run: python3 -m py_compile bwenv.py test_vaultwarden.py
      - name: Unit tests
        run: python3 -m unittest discover -v
